"""`0025_run_completion_insert_seq` against a real PostgreSQL server.

VOYN-W0-AICC-INSERT-SEQ. Skipped unless `AICC_TEST_PG_ADMIN_DSN` is set (see
conftest).

Two tables, two columns, two indexes — and the reason it gets its own suite is
the identity declaration rather than the columns. `GENERATED BY DEFAULT` and
`GENERATED ALWAYS` produce the same `information_schema` column type and the
same index definitions; what separates them is whether an `INSERT` carrying an
explicit value is accepted or refused. The mirror always carries one, and the
dual-write hook swallows what it raises — so getting this backwards produces a
table that simply never mirrors, silently, which is the failure mode this
schema has already paid for once. Nothing but an insert proves it, so there is
an insert.

The reversibility assertion is the one 0002 and 0004 make about themselves: the
schema after a full round trip is indistinguishable from the schema before,
twice over. An identity column drops the sequence it owns along with itself,
which is exactly the kind of residue a name-based `DROP SEQUENCE` would get
wrong — so the snapshot below includes the sequences, not only the columns.
"""

from __future__ import annotations

import pytest

from command_center.db import migrations, roles

pytestmark = pytest.mark.usefixtures("role_passwords")

#: This migration, named rather than taken as `discover()[-1]` — which stops
#: meaning anything the moment a twenty-sixth migration lands, and does so
#: silently.
VERSION = 25

TABLES = ("run", "completion")


def _as_role(dsn: str, role: str, role_passwords: dict[str, str]) -> str:
    from psycopg.conninfo import conninfo_to_dict, make_conninfo

    params = conninfo_to_dict(dsn)
    params.update(user=role, password=role_passwords[role])
    return make_conninfo(**params)


def _provision(admin_conn, psycopg, test_dsn, role_passwords) -> None:
    """Bootstrap as superuser, migrate as the migrator — the production order."""
    roles.apply_bootstrap(admin_conn)
    with psycopg.connect(
        _as_role(test_dsn, roles.MIGRATOR_ROLE, role_passwords), autocommit=True
    ) as conn:
        migrations.upgrade(conn)
        roles.apply_table_grants(conn)


def _shape(admin_conn) -> dict:
    """Everything 0025 touches, and nothing it does not.

    Scoped to `run`/`completion` and to the sequences in the schema: a
    whole-schema snapshot would also move whenever an unrelated migration lands,
    which turns a reversibility failure here into a diff nobody can read. The
    sequence list is in because an identity column's sequence is the residue a
    downgrade is most likely to leave behind — it has a name nothing else ever
    refers to, so nothing else would notice it surviving.
    """
    with admin_conn.cursor() as cur:
        cur.execute(
            "SELECT table_name, column_name, data_type, is_nullable, is_identity, "
            "identity_generation FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ANY(%s) "
            "ORDER BY table_name, ordinal_position",
            (list(TABLES),),
        )
        columns = cur.fetchall()
        cur.execute(
            "SELECT tablename, indexname, indexdef FROM pg_indexes "
            "WHERE schemaname = 'public' AND tablename = ANY(%s) "
            "ORDER BY tablename, indexname",
            (list(TABLES),),
        )
        indexes = cur.fetchall()
        cur.execute(
            "SELECT sequence_name FROM information_schema.sequences "
            "WHERE sequence_schema = 'public' ORDER BY sequence_name"
        )
        sequences = cur.fetchall()
    return {"columns": columns, "indexes": indexes, "sequences": sequences}


def test_the_migration_is_reversible_without_residue(
    admin_conn, psycopg, test_dsn, role_passwords
):
    """up -> down -> up -> down, with the schema equal at every matching point."""
    _provision(admin_conn, psycopg, test_dsn, role_passwords)
    migrator_dsn = _as_role(test_dsn, roles.MIGRATOR_ROLE, role_passwords)
    above = tuple(m.version for m in migrations.discover() if m.version > VERSION)

    with psycopg.connect(migrator_dsn, autocommit=True) as conn:
        assert migrations.downgrade(conn, target=VERSION - 1) == (*above[::-1], VERSION)
        before = _shape(admin_conn)

        assert migrations.upgrade(conn, target=VERSION) == (VERSION,)
        after = _shape(admin_conn)
        assert after != before, "the snapshot notices nothing; it would pass on anything"

        assert migrations.downgrade(conn, target=VERSION - 1) == (VERSION,)
        assert _shape(admin_conn) == before

        assert migrations.upgrade(conn, target=VERSION) == (VERSION,)
        assert _shape(admin_conn) == after

        assert migrations.downgrade(conn, target=VERSION - 1) == (VERSION,)
        assert _shape(admin_conn) == before


@pytest.mark.parametrize("table", TABLES)
def test_the_column_is_identity_by_default_on_both_tables(
    table, admin_conn, psycopg, test_dsn, role_passwords
):
    """`BY DEFAULT`, spelled out, because `ALWAYS` looks identical from outside.

    `information_schema.columns.identity_generation` is the only place the
    difference is legible without attempting a write, and the write it changes
    is the one the mirror makes on every single row.
    """
    _provision(admin_conn, psycopg, test_dsn, role_passwords)
    with admin_conn.cursor() as cur:
        cur.execute(
            "SELECT data_type, is_identity, identity_generation "
            "FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = %s "
            "AND column_name = 'insert_seq'",
            (table,),
        )
        assert cur.fetchone() == ("bigint", "YES", "BY DEFAULT")


@pytest.mark.parametrize("table", TABLES)
def test_the_index_is_the_per_task_newest_first_read(
    table, admin_conn, psycopg, test_dsn, role_passwords
):
    """Composite and in that order: the task is the seek, the sequence is the
    ordering. A bare index on `insert_seq` would answer "what is the newest row
    anywhere", which is not the question anybody asks."""
    _provision(admin_conn, psycopg, test_dsn, role_passwords)
    with admin_conn.cursor() as cur:
        cur.execute(
            "SELECT indexdef FROM pg_indexes "
            "WHERE schemaname = 'public' AND indexname = %s",
            (f"idx_{table}_task_insert_seq",),
        )
        (indexdef,) = cur.fetchone()
    assert "(task_id, insert_seq)" in indexdef, indexdef


def test_a_mirrored_insert_may_carry_the_authoritys_own_value(
    admin_conn, psycopg, test_dsn, role_passwords
):
    """The whole point of `BY DEFAULT`, proven the only way it can be.

    While SQLite is the authority, every `insert_seq` that reaches this database
    is an explicit value the mirror copied. Under `GENERATED ALWAYS` this
    statement raises `428C9` unless it carries `OVERRIDING SYSTEM VALUE` — which
    `PostgresTableMirror` emits only for tables declaring `identity=True`, and
    `run` does not, because its *key* is text. The dual-write hook catches and
    logs at debug, so the mistake would surface as an empty mirror rather than
    as an error anybody sees.
    """
    _provision(admin_conn, psycopg, test_dsn, role_passwords)
    with admin_conn.cursor() as cur:
        cur.execute(
            "INSERT INTO task (id, project, title, task_type, created_at, updated_at) "
            "VALUES ('t-1', 'AICC', 't', 'implementation', now(), now())"
        )
        cur.execute(
            "INSERT INTO session (id, task_id, project, repository_path, created_at, "
            "updated_at) VALUES ('s-1', 't-1', 'AICC', '/tmp/r', now(), now())"
        )
        cur.execute(
            "INSERT INTO run (id, session_id, task_id, sequence, state, project, "
            "task_type, repository_path, prompt, created_at, updated_at, insert_seq) "
            "VALUES ('r-1', 's-1', 't-1', 1, 'COMPLETED', 'AICC', 'implementation', "
            "'/tmp/r', 'p', now(), now(), 4242)"
        )
        cur.execute("SELECT insert_seq FROM run WHERE id = 'r-1'")
        assert cur.fetchone() == (4242,)


def test_resync_identity_advances_the_sequence_past_the_mirrored_values(
    admin_conn, pg_connection_factory
):
    """The cutover step, which is why `BY DEFAULT` is safe rather than merely
    permissive.

    Explicit inserts leave the sequence untouched, so the first value PostgreSQL
    generates for itself would be 1 — a value the mirror has already used. The
    call takes a column name now precisely because this identity column is not
    the key; nothing before 0025 needed that.
    """
    from command_center.db.run_store import PostgresRunMirror

    # `pg_connection_factory` migrates the throwaway database itself, so there
    # is nothing left for `_provision` to do here.
    with admin_conn.cursor() as cur:
        cur.execute(
            "INSERT INTO task (id, project, title, task_type, created_at, updated_at) "
            "VALUES ('t-2', 'AICC', 't', 'implementation', now(), now())"
        )
        cur.execute(
            "INSERT INTO session (id, task_id, project, repository_path, created_at, "
            "updated_at) VALUES ('s-2', 't-2', 'AICC', '/tmp/r', now(), now())"
        )
        cur.execute(
            "INSERT INTO run (id, session_id, task_id, sequence, state, project, "
            "task_type, repository_path, prompt, created_at, updated_at, insert_seq) "
            "VALUES ('r-2', 's-2', 't-2', 1, 'COMPLETED', 'AICC', 'implementation', "
            "'/tmp/r', 'p', now(), now(), 99)"
        )

    mirror = PostgresRunMirror(connection_factory=pg_connection_factory)
    assert mirror.resync_identity("insert_seq") == 99

    with admin_conn.cursor() as cur:
        cur.execute(
            "INSERT INTO run (id, session_id, task_id, sequence, state, project, "
            "task_type, repository_path, prompt, created_at, updated_at) "
            "VALUES ('r-3', 's-2', 't-2', 2, 'COMPLETED', 'AICC', 'implementation', "
            "'/tmp/r', 'p', now(), now()) RETURNING insert_seq"
        )
        assert cur.fetchone() == (100,)


def test_resync_identity_still_refuses_a_column_that_has_no_sequence(
    pg_connection_factory
):
    """The generalisation must not quietly accept nonsense.

    Before 0025 the guard was `spec.identity`, which answered for `id` and for
    nothing else. Now the database is asked — `pg_get_serial_sequence` returns
    NULL for an ordinary column — so a typo'd cutover call fails loudly instead
    of `setval`-ing something that does not exist.
    """
    from command_center.db.run_store import PostgresRunMirror

    mirror = PostgresRunMirror(connection_factory=pg_connection_factory)
    with pytest.raises(TypeError, match="not an identity column"):
        mirror.resync_identity("sequence")
    with pytest.raises(ValueError, match="no column"):
        mirror.resync_identity("nope")
