-- 0025_run_completion_insert_seq (VOYN-W0-AICC-INSERT-SEQ)
--
-- A real insertion-order column on `run` and `completion`, because the query
-- that needs one was leaning on a SQLite implementation detail that has no
-- counterpart here.
--
-- `created_at` is written by `models.iso_now()` — ISO text at *second*
-- resolution on the authority side — so two runs (or two completions) for one
-- task created inside the same second tie, and `ORDER BY created_at DESC`
-- returns an arbitrary one of them. That is the normal case rather than a
-- corner: an automatic rework relaunches a task as soon as its failure is
-- observed, so several runs per task per second is what the pipeline does on
-- purpose. `get_latest_run_for_task` and `get_completion_by_task` therefore
-- broke the tie on SQLite's implicit `rowid`. PostgreSQL has no such column,
-- so once reads move here the identical query would silently resolve ties
-- arbitrarily again — the mirror would be structurally incapable of answering
-- a question the authority answers, and nothing would say so.
--
-- Neither of the two columns that look like they already answer it does:
-- `run.sequence` counts within a *session*, and the supervisor opens a new
-- session for every non-resume launch, so a task relaunched N times holds N
-- runs all at `sequence = 1`; `completion` has no such column at all. The
-- text keys are no help either — run ids are `uuid4().hex`, and the caller may
-- supply one.
--
-- THE IDENTITY DECISION, and it is the opposite of the one 0001 makes for its
-- surrogate keys:
--
--   `GENERATED BY DEFAULT AS IDENTITY`, not `GENERATED ALWAYS`.
--
-- While SQLite is the authority every `insert_seq` arrives from the mirror as
-- an explicit value. `GENERATED ALWAYS` refuses an explicit value outright
-- unless the statement carries `OVERRIDING SYSTEM VALUE`, and the dual-write
-- hook swallows the raise — the columns would simply never mirror, silently,
-- which is the failure mode `table_mirror`'s `identity` flag exists to avoid
-- and the one this schema has already been bitten by. `BY DEFAULT` takes the
-- authority's value as given and keeps a usable sequence for the native writes
-- that begin at cutover; `PostgresRunMirror.resync_identity("insert_seq")` is
-- the cutover step that advances the sequence past the largest mirrored value,
-- exactly as `model_event` already does for its `id`.
--
-- Existing rows are assigned values from the new sequence in whatever physical
-- order the table happens to be in. That order is not the authority's, and it
-- is deliberately not patched up here: every one of those rows is overwritten
-- with the authority's own `insert_seq` on its next mirrored write, and until
-- reads move, the authority is the only thing anybody orders by. There is no
-- unique index on the column for that same reason — during dual-write the
-- generated values and the mirrored values coexist until each row is next
-- mirrored, and a uniqueness constraint would turn that overlap into an insert
-- failure the dual-write hook swallows. The authority does not carry one
-- either: the values are unique because they are minted as `MAX + 1` under
-- `BEGIN IMMEDIATE`, and declaring the constraint on one engine only is the
-- divergence `tests/db/test_schema_correspondence.py` exists to reject.
--
-- No entry is added to `roles.IDENTITY_SEQUENCES` and no `USAGE ON SEQUENCE`
-- grant goes with these two. That table maps identity *primary keys* to their
-- sequences so an inserting role can advance them, and a role only needs that
-- when it inserts without naming the column — which, for as long as SQLite is
-- the authority, no role ever does: the value is always supplied. The grant
-- belongs with the cutover that starts native writes, alongside the
-- `resync_identity` call, and granting it now would hand out a right nothing
-- exercises and nothing would notice going stale.

ALTER TABLE run ADD COLUMN insert_seq bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE completion ADD COLUMN insert_seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- Two indexes per table, matching the authority's, because the correspondence
-- check compares column sets rather than counts.
--
-- `(insert_seq)` serves the stamp itself: the authority mints
-- `MAX(insert_seq) + 1` over the whole table inside the write lock, and without
-- an index leading on the column every insert would pay a full scan while
-- holding it. It stays on this side once reads move, for the same statement.
CREATE INDEX idx_run_insert_seq ON run (insert_seq);

CREATE INDEX idx_completion_insert_seq ON completion (insert_seq);

-- `(task_id, insert_seq)` is the read this column exists for: newest-first
-- within one task. Composite and in that order so the task is the seek and the
-- sequence is the ordering, which is what makes the "which run is newest"
-- lookup a bounded index scan rather than a sort over every run the task ever
-- had.
CREATE INDEX idx_run_task_insert_seq ON run (task_id, insert_seq);

CREATE INDEX idx_completion_task_insert_seq ON completion (task_id, insert_seq);
