"""Accessibility repairs for semantics generated by Streamlit's app shell.

Streamlit owns the outer document, so Python widgets cannot set these
attributes directly. A static inline script keeps the repair attached across
incremental renders and reruns without changing visible content.
"""

from __future__ import annotations

import streamlit as st


_SHELL_REPAIR = """
<script>
(() => {
  const document = window.parent.document;
  const stateKey = "__aiccAccessibilityRepair";
  const state = window.parent[stateKey] || {
    activeObservers: 0,
    callbackCount: 0,
    installCount: 0,
    observer: null,
  };

  const repair = () => {
    const main = document.querySelector("section[data-testid='stMain']");
    if (main) main.removeAttribute("tabindex");

    const sidebar = document.querySelector("section[data-testid='stSidebar']");
    if (sidebar) {
      sidebar.removeAttribute("aria-expanded");
      sidebar.setAttribute("role", "navigation");
      sidebar.setAttribute("aria-label", "Основная навигация");
    }

    document.querySelectorAll(
      "[data-testid='stHeaderActionElements'] a, " +
      "a[data-testid='stHeaderActionElements']"
    )
      .forEach((anchor) => {
        anchor.setAttribute("aria-hidden", "true");
        anchor.setAttribute("tabindex", "-1");
      });

    const iconLabels = {
      keyboard_double_arrow_left: "Скрыть навигацию",
      keyboard_double_arrow_right: "Показать навигацию",
      menu: "Открыть навигацию",
      close: "Закрыть",
    };
    document.querySelectorAll("button [data-testid='stIconMaterial']")
      .forEach((icon) => {
        const button = icon.closest("button");
        if (button && !(button.getAttribute("aria-label") || "").trim()) {
          const label = iconLabels[icon.textContent.trim()];
          if (label) button.setAttribute("aria-label", label);
        }
        icon.setAttribute("aria-hidden", "true");
      });
  };

  const install = () => {
    if (state.observer) {
      state.observer.disconnect();
      state.activeObservers -= 1;
    }
    repair();
    state.observer = new MutationObserver(() => {
      state.callbackCount += 1;
      repair();
    });
    state.observer.observe(document.body, {
      childList: true,
      subtree: true,
      // Streamlit's resizable sidebar re-applies aria-expanded as an *attribute*
      // mutation (not a node insertion) on resize/rerun, which a childList-only
      // observer never sees — so the invalid attribute silently reappears after
      // the initial repair (axe: aria-allowed-attr, critical). Watching just
      // that one attribute closes the gap without a feedback loop: removing an
      // absent attribute emits no mutation, and the other repairs set
      // attributes outside this filter.
      attributes: true,
      attributeFilter: ["aria-expanded"],
    });
    state.activeObservers += 1;
    state.installCount += 1;
  };

  window.parent[stateKey] = state;
  window.parent.__aiccInstallAccessibilityRepair = install;
  install();
})();
</script>
"""


def repair_streamlit_shell_semantics() -> None:
    """Remove non-content tab stops and decorative accessible names."""
    st.html(_SHELL_REPAIR, unsafe_allow_javascript=True)
