"""Strict parsing and atomic replacement of the worker credential file.

The systemd ``EnvironmentFile`` is also the hand-off between the rotator and
already-running workers.  Treat it as a small configuration format rather than
feeding it through a shell: duplicate keys, shell syntax and malformed lines
are refused, and updating the password preserves every unrelated setting.
"""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

_KEY = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


class CredentialFileError(RuntimeError):
    """The credential file cannot be consumed without guessing."""


@dataclass(frozen=True, slots=True)
class PreparedCredentialFile:
    target: Path
    temporary: Path

    def commit(self) -> None:
        os.replace(self.temporary, self.target)
        directory_fd = os.open(self.target.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)

    def discard(self) -> None:
        try:
            self.temporary.unlink()
        except FileNotFoundError:
            pass


def read_environment_file(path: str | os.PathLike[str]) -> dict[str, str]:
    """Read the supported, deliberately shell-free EnvironmentFile subset."""

    source = Path(path)
    try:
        text = source.read_text(encoding="utf-8")
    except OSError as error:
        raise CredentialFileError(f"cannot read credential file: {error}") from error
    return parse_environment_text(text)


def parse_environment_text(text: str) -> dict[str, str]:
    """Parse the EnvironmentFile subset from already-read text.

    Callers that must read through a validated file descriptor (O_NOFOLLOW +
    fstat-on-the-fd, e.g. rotation crash recovery) parse via this function so
    the open they validated is the open they consume.
    """
    # split("\n"), not splitlines(): Python's splitlines also breaks on
    # \x0b/\x0c/\x1c-\x1e/\x85/U+2028/U+2029, which systemd treats as
    # ordinary value bytes -- the split would hide them from the value
    # validation below and parse a different language than systemd
    # (independent-review finding on 61c73e7).
    lines = text.split("\n")
    values: dict[str, str] = {}
    for number, raw in enumerate(lines, 1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in raw:
            raise CredentialFileError(f"line {number}: expected KEY=VALUE")
        key, value = raw.split("=", 1)
        key = key.strip()
        if not _KEY.fullmatch(key):
            raise CredentialFileError(f"line {number}: invalid environment key")
        if key in values:
            raise CredentialFileError(f"line {number}: duplicate key {key}")
        if "\x00" in value or "\n" in value or "\r" in value:
            raise CredentialFileError(f"line {number}: invalid value for {key}")
        # Secrets generated by the rotator are hex and need no shell quoting.
        # Refusing quotes/expansion avoids interpreting a different language
        # than systemd when this file is reloaded inside the worker process.
        cleaned = value.strip()
        # Validate the STRIPPED value -- the one actually stored: a leading
        # space used to sneak a quoted value past this check while systemd
        # parses the same line unquoted (independent-review finding on
        # 61c73e7).
        if cleaned[:1] in {"'", '"'} or "$" in cleaned or "`" in cleaned:
            raise CredentialFileError(
                f"line {number}: shell syntax is not supported for {key}"
            )
        if "\r" in cleaned or "\x00" in cleaned:
            raise CredentialFileError(
                f"line {number}: control characters are not supported for {key}"
            )
        values[key] = cleaned
    return values


def prepare_password_update(
    path: str | os.PathLike[str], new_password: str
) -> PreparedCredentialFile:
    """Fsync a same-directory replacement, but do not make it live yet.

    Preparing before the database mutation closes the dangerous ordering where
    PostgreSQL knows the new secret but a full filesystem prevents persisting
    it.  The caller commits immediately after the successful rotation.
    """

    target = Path(path)
    if not new_password or any(char in new_password for char in "\r\n\x00"):
        raise CredentialFileError("new password is not EnvironmentFile-safe")
    values = read_environment_file(target)
    if "AICC_PG_PASSWORD" not in values:
        raise CredentialFileError("AICC_PG_PASSWORD is missing")

    stat = target.stat()
    rendered: list[str] = []
    replacements = 0
    for raw in target.read_text(encoding="utf-8").splitlines(keepends=True):
        if raw.strip() and not raw.lstrip().startswith("#") and "=" in raw:
            key = raw.split("=", 1)[0].strip()
            if key == "AICC_PG_PASSWORD":
                newline = "\n" if raw.endswith("\n") else ""
                rendered.append(f"AICC_PG_PASSWORD={new_password}{newline}")
                replacements += 1
                continue
        rendered.append(raw)
    if replacements != 1:
        raise CredentialFileError("AICC_PG_PASSWORD must occur exactly once")

    fd, name = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    temporary = Path(name)
    try:
        os.fchmod(fd, stat.st_mode & 0o777)
        try:
            os.fchown(fd, stat.st_uid, stat.st_gid)
        except PermissionError:
            # A non-root rotator normally owns the file.  If it does not, the
            # replacement must still have exactly the original ownership.
            current = os.fstat(fd)
            if (current.st_uid, current.st_gid) != (stat.st_uid, stat.st_gid):
                raise
        stream = os.fdopen(fd, "w", encoding="utf-8")
        # fdopen took ownership: a failure inside the with-block closes fd via
        # the context manager, and closing it AGAIN here would hit a recycled
        # descriptor number (independent-review finding on 61c73e7).
        fd = -1
        with stream:
            stream.writelines(rendered)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        if fd != -1:
            try:
                os.close(fd)
            except OSError:
                pass
        temporary.unlink(missing_ok=True)
        raise
    return PreparedCredentialFile(target=target, temporary=temporary)
